#!/bin/bash
set -e

# It takes ages on Docker to run the app without this
export MAVEN_OPTS="${MAVEN_OPTS} -Djava.security.egd=file:///dev/urandom"

function outputFolder() {

 echo "target"
 
}

function propagatePropertiesForVersion() {
    local version="${1}"
    local fileLocation="${2:-${OUTPUT_FOLDER}/version.properties}"
    rm -rf "${fileLocation}"
    echo "PIPELINE_VERSION=${version}" >> ${fileLocation}
    echo "Resolved properties"
    cat ${fileLocation}
}

export OUTPUT_FOLDER=$( outputFolder )
####################################################
# Application Build, Unit Test, Upload Artifactory
####################################################
echo "OUTPUT_FOLDER" "${OUTPUT_FOLDER}"
echo "PIPELINE_VERSION" "${PIPELINE_VERSION}"

./mvnw versions:set -DnewVersion=${PIPELINE_VERSION} ${MAVEN_ARGS}
./mvnw clean verify deploy -s /home/kkanzo/.m2/settings.xml -Punit -Ddistribution.management.release.id=${M2_SETTINGS_REPO_ID} -Ddistribution.management.release.url=${REPO_WITH_JARS} ${MAVEN_ARGS}
    
propagatePropertiesForVersion ${PIPELINE_VERSION}
